### PR TITLE
Fix: Jaws highlight issue for close button (fixes #113)

### LINKED ISSUE #113: Issue with Jaws highlighting the close popup button
### Subject of the issue/enhancement/features
This issue seems to be Jaws specific, but when you select the close button the highlight box for it is much bigger and highlights nearly the whole of the notify box. 

This seems to be linked to the non breaking space (\&nbsp;) in the a11y-focusguard, when removed the highlight box seems to work as expected. 

### Your environment
* FW v5.25.2, Hotgrid v4.3.5
* Chrome with Jaws 2023

### Steps to reproduce
With Jaws (2023) open an item and navigate to the close button.

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
Fixes #113 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Jaws highlight issue for close button (fixes #113)

[//]: # (List appropriate steps for testing if needed)
### Testing
1. Using Jaws (2023), open a hotgrid item and navigate to the close button
2. Check the highlight box of the button 

[//]: # (Mention any other dependencies)

### CODE REVIEW

**Review by swashbuck — APPROVED** [review]
👍

File: templates/hotgridPopupToolbar.jsx [hunk 1]
```diff
@@ -74,7 +74,7 @@ export default function HotgridPopupToolbar(props) {
       </button>
 
       {a11yConfig._options._isPopupWrapFocusEnabled &&
-      <a className="a11y-focusguard a11y-ignore a11y-ignore-focus" tabIndex="0" role="presentation">&nbsp;</a>
+      <a className="a11y-focusguard a11y-ignore a11y-ignore-focus" tabIndex="0" role="presentation"></a>
```
Comment (kirsty-hames) [inline templates/hotgridPopupToolbar.jsx:77]: If removing the no breaking space could this be amended to
`<a className="a11y-focusguard a11y-ignore a11y-ignore-focus" tabIndex="0" role="presentation" />` for consistency with Hotgraphic popup https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/templates/hotgraphicPopupToolbar.jsx
