### PR TITLE
Fix: Remove this.render on device change (fixes #137)

### LINKED ISSUE #137: Renders multiple instances of Hint on Hotgrid components
Due to the Hotgraphic component having both a desktop Hotgraphic and Narrative mobile view, the Hint renders twice

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
#137 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Remove this.render on device change (fixes #137)

### CODE REVIEW

File: js/HotgridView.js [hunk 1]
```diff
@@ -32,10 +27,6 @@ class HotgridView extends ComponentView {
     }
   }
 
-  resizeControl() {
-    this.render();
```
Comment (oliverfoster) [inline js/HotgridView.js:36]: this.changed() rather than this.render() ?

**Comment by oliverfoster** [comment]
👍 excellent

**Review by oliverfoster — APPROVED** [review]

**Review by kirsty-hames — APPROVED** [review]
Works as expected thanks. Tested on Mac Safari, Chrome, FF and Chrome on Android tablet.
