### PR TITLE
Fix: ES6/JSX conversion and schema AAT update (fixes #92)

### LINKED ISSUE #92: Convert to ES6/JSX
Convert hotgrid.hbs and hotgridPopup.hbs to JSX.

### LINKED ISSUE #94: Add support for authoring tool 1
As per core issue https://github.com/adaptlearning/adapt_framework/issues/2704

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #92 
Fixes #94 

## Notable changes:

- Moved DOM manipulations to the template
- #94 Changed reference to _globals._accessibility._ariaLabels.item
- Moved popup toolbar into new template
- Created itemAriaLabel() to construct the aria-label for each Hotgrid button

## Schema updates
- Created course and component schema files via adapt-octopus.
- _globals._accessibility._ariaLabels.item seemed to be missing from properties.schema. I've added this as a new property of _hotgrid and modified the template accordingly (
https://github.com/cgkineo/adapt-hotgrid/pull/97 ). Question: should we add the previously expected property for backwards compatibility with the hbs template?

### CODE REVIEW

**Comment by swashbuck** [comment]
@kirsty-hames @guywillis I noticed that the current JS adds an `is-mobile` or `is-desktop` class based on the device width.  However, these classes are not defined anywhere.  Wondering if we can remove them from the JS altogether?

Also, in setUpColumns(), an inline style is added to determine the width if the device size is 'large.'  An alternate approach would be to do this all with media queries and remove the inline style.  We'd set up a handful of column classes (ex. `has-3-columns`, `has-4-columns`, etc.), and those would control the width via media queries and CSS.  Thoughts?

**Comment by StuartNicholls** [comment]
Generally speaking its probably worth having a catch-up about inline classes / css selector stuff. Perfect topic for FED Team meeting I think.

**Comment by swashbuck** [comment]
> I think there's many ways we could handle the column layouts in CSS and worth discussing. Maybe this can be raised as a new issue separete to this PR?

@kirsty-hames @StuartNicholls I've created #98 for looking into a new way to implement the column layouts.

**Comment by swashbuck** [comment]
> Debounce required as a second (bad) click event is dispatched on iOS causing a jump of two items.

In HotgridPopupView.js, I wasn't sure if this was still an issue?  So, the debounced line is currently commented out.

**Review by chris-steele — APPROVED** [review]

**Comment by StuartNicholls** [comment]
> > I think there's many ways we could handle the column layouts in CSS and worth discussing. Maybe this can be raised as a new issue separete to this PR?
> 
> @kirsty-hames @StuartNicholls Agreed. I've created #98 for looking into a new way to implement the column layouts.

Yes, agreed. Separate PR is the way forward. We need to consider other components and Adapt as a whole. For Example, I'd say use css grids and either set a css variable and use the selector in the theme or just write it to a separate stylesheet in the JS is the best way forward. But, that would require some thought about other applications of inline css and then if we were to do that, we probably should add helpers to Adapt.

So in my example cols might look something like this:

`
 [JSON]

columns: {
  _large: 5,
  _medium: 3,
  _small: 1
}

[OUTPUT]

--number-of-hotgrid-cols: [set via JS];

[THEME CSS]

display: grid;
grid-template-columns: repeat(--number-of-hotgrid-cols, 1fr);
`

File: js/HotgridView.js [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+
+class HotgridView extends ComponentView {
+
+  initialize(...args) {
+    super.initialize(...args);
+
+    this.onItemClicked = this.onItemClicked.bind(this);
+
+    this.setUpViewData();
+    this.setUpColumns();
```
Comment (StuartNicholls) [inline js/HotgridView.js:15]: Do we need this here as the function is called in postRender ?

File: templates/hotgrid.jsx [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+        <div className="hotgrid__grid" role="list">
+
+          {_items.map(({ _index, _graphic, _isVisited, _isActive }) =>
+
+            <div className="hotgrid__item" role="listitem" key={_index} style={{ width: _columnWidth + '%' }}>
+
+              <button className={classes([
+                'hotgrid__item-btn',
+                `item-${_index}`,
+                (_graphic.srcHover && _graphic.srcVisited) ? 'is-image' : 'is-css',
```
Comment (StuartNicholls) [inline templates/hotgrid.jsx:52]: rather than is-css can't this be more descriptive so something like has-css-states or has-css-rollover-states or something along those lines

File: templates/hotgridPopup.jsx [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+          'hotgrid-popup__item',
+          _classes,
+          _isRound && 'is-round',
+          _isVisited && 'is-visited',
+          _isActive && 'is-active',
+          _imageAlignment && `align-image-${_imageAlignment}`
+        ])}
+        key={index}
+        data-index={index}
+        aria-hidden={!_isActive && null}
```
Comment (StuartNicholls) [inline templates/hotgridPopup.jsx:35]: Rather than render out aria-hidden='false' when its not hidden can we just not have that in that case pls? So only renders out aria-hidden=true when true pls

File: templates/hotgrid.jsx [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+                _isRound && 'is-round',
+                _isVisited && 'is-visited',
+                _isActive && 'is-active'
+              ])}
+              onClick={onItemClicked}
+              data-index={_index}
+              >
+
+                <span className="aria-label" dangerouslySetInnerHTML={ itemAriaLabel(_index, _graphic, _isVisited) } />
```
Comment (StuartNicholls) [inline templates/hotgrid.jsx:61]: Is visited states need to go at the beginning of the label. We're applying this globally but might as well update as we go

File: templates/hotgrid.jsx [hunk 5]
```diff
@@ -0,0 +1,108 @@
...
+
+      <div className="component__widget hotgrid__widget">
+
+        <div className="hotgrid__grid" role="list">
+
+          {_items.map(({ _index, _graphic, _isVisited, _isActive }) =>
+
+            <div className="hotgrid__item" role="listitem" key={_index} style={{ width: _columnWidth + '%' }}>
+
+              <button className={classes([
```
Comment (StuartNicholls) [inline templates/hotgrid.jsx:49]: Button states need aria-haspopup="dialog"

File: templates/hotgridPopupToolbar.jsx [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+    onCloseClick,
+    onControlClick,
+    shouldEnableBack,
+    shouldEnableNext,
+    itemCount,
+    _hidePagination
+  } = props;
+
+  return (
+    <div className={classes([
```
Comment (StuartNicholls) [inline templates/hotgridPopupToolbar.jsx:19]: Strictly speaking the DOM order should reflect the visual order for accessibility reasons. So should render at the top rather than the bottom of the pop up items

File: templates/hotgridPopupToolbar.jsx [hunk 7]
```diff
@@ -0,0 +1,80 @@
...
+
+      </div>
+      }
+
+      <button
+        className="btn-icon hotgrid-popup__close"
+        aria-label={ariaLabels.onCloseClick}
+        onClick={onCloseClick}
+      >
+        <span className="icon" />
```
Comment (StuartNicholls) [inline templates/hotgridPopupToolbar.jsx:71]: icons need aria-hidden

File: templates/hotgridPopupToolbar.jsx [hunk 8]
```diff
@@ -0,0 +1,80 @@
...
+          className={classes([
+            'btn-icon hotgrid-popup__controls next',
+            !shouldEnableNext && 'is-disabled'
+          ])}
+          aria-label={ariaLabels.next}
+          aria-disabled={!shouldEnableNext}
+          onClick={onControlClick}
+          data-direction='next'
+        >
+          <span className="icon" />
```
Comment (StuartNicholls) [inline templates/hotgridPopupToolbar.jsx:60]: Aira-hidden needed here

File: templates/hotgridPopupToolbar.jsx [hunk 9]
```diff
@@ -0,0 +1,80 @@
...
+          className="hotgrid-popup__count"
+          dangerouslySetInnerHTML={{ __html: itemCount }}
+        />
+
+        <button
+          className={classes([
+            'btn-icon hotgrid-popup__controls next',
+            !shouldEnableNext && 'is-disabled'
+          ])}
+          aria-label={ariaLabels.next}
```
Comment (StuartNicholls) [inline templates/hotgridPopupToolbar.jsx:55]: Aira-label needs to be much more detailed here so should say - 'Forward to item 2 (item 2 of 3)'.

I think the hotgraphic follows this convention but says - 'Forward to Hot Graphic item 2 (item 2 of 3)' - Im not sure 'hot-graphic' is necessary there, may need to raise an issue on thee hot-graphic repo.

In general though the pop -up should be wcag compliant and follow the carousel behaviour here:

https://www.w3.org/WAI/tutorials/carousels/

This has already been implemented got hot-graphic here:

https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/244

So you can use that as a reference to check. Happy to have this one in a separate PR if need be

**Review by StuartNicholls — COMMENTED** [review]
Added some single line comments. I think the minor ones accessibility ones we might as well get done in this PR (and is good for best practice). Happy to have a separate PR(s) for other bits if it proves complicated.

File: templates/hotgridPopup.jsx (hunk 3 above)
Comment (swashbuck) [reply templates/hotgridPopup.jsx]: Fixed. I had this logic backwards.

File: templates/hotgridPopupToolbar.jsx (hunk 9 above)
Comment (swashbuck) [reply templates/hotgridPopupToolbar.jsx:55]: Noting that this fix will close #89.

File: templates/hotgrid.jsx (hunk 5 above)
Comment (swashbuck) [reply templates/hotgrid.jsx:49]: Fixed.

File: templates/hotgridPopupToolbar.jsx (hunk 7 above)
Comment (swashbuck) [reply templates/hotgridPopupToolbar.jsx]: Fixed.

File: templates/hotgridPopupToolbar.jsx [hunk 10]
```diff
@@ -0,0 +1,80 @@
...
+          className={classes([
+            'btn-icon hotgrid-popup__controls back',
+            !shouldEnableBack && 'is-disabled'
+          ])}
+          aria-label={ariaLabels.previous}
+          aria-disabled={!shouldEnableBack}
+          onClick={onControlClick}
+          data-direction='back'
+        >
+          <span className="icon" />
```
[the remark this answers is not in the document]
Comment (swashbuck) [reply templates/hotgridPopupToolbar.jsx]: Fixed.

File: templates/hotgridPopupToolbar.jsx (hunk 8 above)
Comment (swashbuck) [reply templates/hotgridPopupToolbar.jsx]: Fixed.

File: templates/hotgrid.jsx (hunk 4 above)
Comment (swashbuck) [reply templates/hotgrid.jsx:62]: Moved 'visited' to the beginning.

File: js/HotgridView.js (hunk 1 above)
Comment (swashbuck) [reply js/HotgridView.js]: Nope, unnecessary.  Fixed.

File: templates/hotgridPopupToolbar.jsx (hunk 6 above)
Comment (swashbuck) [reply templates/hotgridPopupToolbar.jsx:19]: Done.

File: templates/hotgrid.jsx (hunk 2 above)
Comment (swashbuck) [reply templates/hotgrid.jsx:52]: I think `has-css-states` could work since the class applies to default, hover and visited states.  Thoughts, fellow FEDs? @kirsty-hames @guywillis @joe-replin

File: templates/hotgridPopupToolbar.jsx (hunk 9 above)
Comment (swashbuck) [reply templates/hotgridPopupToolbar.jsx]: This is ready for review.  Requires the schema updates from #94 .

I noticed that Hot Graphic's controls don't seem to take into account `_canCycleThroughPagination` being enabled.  So, I've adapted and modified the logic for Hot Grid.  Probably should be fixed in Hot Graphic, though. So, when `_canCycleThroughPagination` is false and the back or next button is disabled, the aria-label will simply read "back" or "next" respectively.  Otherwise, it will correctly say what the next or previous item number is.

> I think the hotgraphic follows this convention but says - 'Forward to Hot Graphic item 2 (item 2 of 3)' - Im not sure 'hot-graphic' is necessary there, may need to raise an issue on thee hot-graphic repo.

@StuartNicholls This uses the item's title rather than automatically including the "Hot Graphic" plugin name.  Are you saying we don't need the title at all and should just use "forward to item 2"?

Comment (StuartNicholls) [reply templates/hotgridPopupToolbar.jsx]: My bad! Title needs to stay :)

Comment (swashbuck) [reply templates/hotgridPopupToolbar.jsx]: Looks like I broke the popup focus.  It should always focus on the notify title not the back button.  Will investigate tomorrow.

Comment (swashbuck) [reply templates/hotgridPopupToolbar.jsx]: ^^ should be fixed.

File: templates/hotgrid.jsx (hunk 2 above)
Comment (StuartNicholls) [reply templates/hotgrid.jsx:52]: Shall we just go with has-css-states to get this merged?

**Review by StuartNicholls — COMMENTED** [review]
Looks good, just the class name change needed

File: templates/hotgrid.jsx (hunk 2 above)
Comment (swashbuck) [reply templates/hotgrid.jsx]: Done

**Review by StuartNicholls — APPROVED** [review]

**Comment by swashbuck** [comment]
I've tested this in AATv1 and it seems fine.  Ready for others to test.
