### PR TITLE
Fix: Converted inline item width to CSS variable (fixes #158)

### LINKED ISSUE #158: Set item widths with CSS class instead of calculated inline style
### Subject of the issue
Currently, item widths are set as inline width styles. 

https://github.com/cgkineo/adapt-hotgrid/blob/ed04d61f8998e4c2e424d3a099d33e723e22742e/templates/hotgrid.jsx#L64-L66

This results in the width being set as an inline style.

```
<div class="hotgrid__item" role="listitem" style="width: 33.3333%;">
```

This would be easier to override in a custom theme if a class was used instead. For example, when the component is set to use 3 columns, add `has-3-columns` to the `component__widget`. The styles would then determine how wide each item should be. For example:

```
.has-3-columns .hotgrid__item {
   width: 33%;
}
```

In a custom theme, if we then needed the items to only be 30% width instead of 33%, we would simply add it to the theme:

```
.has-3-columns .hotgrid__item {
   width: 30%;
}
```

This would also make it easier to adjust the width at different breakpoints as we can rely on `@media` queries in the Less.

### PR DESCRIPTION
**Pull request by guywillis**
Fixes: #158

### Fix
* Converted inline item width to CSS variable

### CODE REVIEW

File: js/HotgridView.js [hunk 1]
```diff
@@ -12,13 +12,28 @@ class HotgridView extends ComponentView {
...
+  }
+
+  setItemWidth() {
+    const item = this.el.style;
+    item.setProperty('--adapt-hotgrid-item-width', 50 + '%');
+
+    const _columns = this.model.get('_columns');
+    if (!_columns || !device.isScreenSizeMin('medium')) return;
+    item.setProperty('--adapt-hotgrid-item-width', `${100 / _columns}%`);
+  }
```
Comment (oliverfoster) [inline js/HotgridView.js:35]:
```suggestion
  setItemWidth() {
    const columns = this.model.get('_columns');
    const width = (!columns || !device.isScreenSizeMin('medium'))
      ? '50%'
      : `${100 / _columns}%`;
    this.el.style.setProperty('--adapt-hotgrid-item-width', 50 + '%');
  }
```

File: less/hotgrid.less [hunk 2]
```diff
@@ -7,7 +7,7 @@
   }
 
   &__item {
-    width: 50%;
+    width: var(--adapt-hotgrid-item-width);
```
Comment (swashbuck) [inline less/hotgrid.less:10]: Won't this change the item width for all Hot Grids on the page? So, you would not be able to use 3 and 4 column Hot Grids on the same page?

**Comment by swashbuck** [comment]
I guess my issue with the CSS variable approach is that it makes the following difficult:

> In a custom theme, if we then needed the items to only be 30% width instead of 33%, we would simply add it to the theme:

```
.has-3-columns .hotgrid__item {
   width: 30%;
}
```

> This would also make it easier to adjust the width at different breakpoints as we can rely on @media queries in the Less.

```
@media (min-width: 10rem) and (max-width: 20rem) {
  .has-3-columns .hotgrid__item {
     width: 23%;
  }
}
```

**Comment by oliverfoster** [comment]
Could you explain how you propose to fix this part of my previous comment:

> You'd have to specify `has-x-columns` classes for all of the available `x` options

Such that all of the correct width values are present with predefined classes:

```css
.has-2-columns .hotgrid__item {
   width: 50%;
}

.has-3-columns .hotgrid__item {
   width: 33%;
}

.has-4-columns .hotgrid__item {
   width: 25%;
}

.has-5-columns .hotgrid__item {
   width: 20%;
}
```

Would you use a mixin and add all of the possible classes to the less output (2-10 columns?), would you have to manually add more classes if you needed more columns?

Note: We added configuration classes like this a lot on previous components and menus (narrative, cover, blinds, etc) and it's very brittle and limited and irritating to write and understand and change and always add excess less that isn't used to every project. Width values should be calculated at runtime rather than being predefined, it's easier and simpler.

When adding the class `has-x-columns` to the component element, a component with `has-3-columns` would need to switch to `has-2-columns` and back at the small-medium transition, as columns always collapse to 2/50% width on mobile.

You could add the '.has-${_columns}-columns' class to the component element, without predefining the class widths, and carry on using the css variables to calculate the widths. This way it would be be possible to calculate the widths at runtime and/or override specific column settings using classes only.

It sounds as though you'd like to change all X column hotgrids in one override whereas the CSS variable implementation is just to switch inline defined widths to class-based widths.

File: js/HotgridView.js [hunk 3]
```diff
@@ -12,13 +12,28 @@ class HotgridView extends ComponentView {
...
+  setUpEventListeners() {
+    this.listenTo(Adapt, 'device:changed', this.setItemWidth);
+  }
+
+  setItemWidth() {
+    const columns = this.model.get('_columns');
+    const shouldCalculateColumns = (columns && device.isScreenSizeMin('medium'));
+    const width = shouldCalculateColumns
+      ? `${100 / columns}%`
+      : '50%';
```
Comment (oliverfoster) [inline js/HotgridView.js:33]:
```suggestion
    const fallbackColumns = 2;
    const shouldCalculateColumns = Boolean(columns && device.isScreenSizeMin('medium'));
    this.$el
      .toggleClass(`has-${columns}-columns`, shouldCalculateColumns)
      .toggleClass(`has-${fallbackColumns}-columns`, !shouldCalculateColumns);
    const calculatedColumns = shouldCalculateColumns
      ? columns 
      : fallbackColumns;
    const width = `${100 / calculatedColumns}%`;
```

File: js/HotgridView.js [hunk 4]
```diff
@@ -12,13 +12,28 @@ class HotgridView extends ComponentView {
...
+    this.el.style.setProperty('--adapt-hotgrid-item-width', width);
+  }
```
Comment (oliverfoster) [inline js/HotgridView.js:35]:
```suggestion
  setItemWidth() {
    const columns = this.model.get('_columns');
    const fallbackColumns = 2;
    const shouldCalculateColumns = Boolean(columns && device.isScreenSizeMin('medium'));
    this.$el
      .toggleClass(`has-${columns}-columns`, shouldCalculateColumns)
      .toggleClass(`has-${fallbackColumns}-columns`, !shouldCalculateColumns);
    const calculatedColumns = shouldCalculateColumns
      ? columns 
      : fallbackColumns;
    const width = `${100 / calculatedColumns}%`;
    this.el.style.setProperty('--adapt-hotgrid-item-width', width);
  }
```

**Comment by swashbuck** [comment]
> You'd have to specify has-x-columns classes for all of the available x options

@oliverfoster This doesn't concern me that much as we can always specify "up to" a reasonable amount of options and use a mixin to create the classes. Unused styles are also unavoidable in many cases, so it doesn't bother me to have unused column classes hanging around (like the Vanilla theme's column classes).

> Width values should be calculated at runtime rather than being predefined, it's easier and simpler.

I think this is an issue of separating styling from presentation/code. Style values should all live in the theme if possible.

> It sounds as though you'd like to change all x column hotgrids in one override whereas the CSS variable implementation is just to switch inline defined widths to class-based widths, which are easier to override without an !important directive.

Yes, classes are much easier to override and changes would most likely be at a global level.

Also, I haven't looked at your recent commit(s). But as long as we have something like `has-x-columns` as a class, I can work with that for any custom theme work.

**Review by oliverfoster — APPROVED** [review]

**Review by swashbuck — APPROVED** [review]
👍

File: js/HotgridView.js [hunk 5]
```diff
@@ -12,13 +12,33 @@ class HotgridView extends ComponentView {
...
+
+  setItemWidth() {
+    const columns = this.model.get('_columns');
+    const fallbackColumns = 2;
+    const shouldCalculateColumns = Boolean(columns && device.isScreenSizeMin('medium'));
+    this.$el
+      .toggleClass(`has-${columns}-columns`, shouldCalculateColumns)
+      .toggleClass(`has-${fallbackColumns}-columns`, !shouldCalculateColumns);
+    const calculatedColumns = shouldCalculateColumns
+      ? columns
```
Comment (kirsty-hames) [inline js/HotgridView.js:36]: remove trailing space

**Review by kirsty-hames — APPROVED** [review]
Works great thanks 👍 minor comment added regarding trailing space
